execute: 
  enabled: true
format:
    revealjs:
        theme: [bg-light.scss]
        logo: img/BG_logo.png
        footer: "[brainglobe.info](https://brainglobe.info) | 2026-06-05"
        slide-number: c
        menu:
          numbers: true
          useTextContentForMissingTitles: false 
          hideMissingTitles: true
        chalkboard: true
        scrollable: false
        preview-links: false
        view-distance: 10
        mobile-view-distance: 10
        auto-animate: true
        auto-play-media: false
        code-overflow: wrap
        highlight-style: atom-one
        mermaid: 
          theme: neutral
          fontFamily: arial
          curve: linear
          